### ISSUE TITLE
BSL Interpreters

### ISSUE THREAD

**Issue by rawkode** [KubeHuddle/KubeHuddle#10]
- [ ] Track 1
- [ ] Track 2

**Comment by rawkode** [comment]
[ ] Speak to DevOpsDays Birmingham about BSL company

**Comment by mjslane** [comment]
Kaluza are interested in sponsoring this. They'd like a quote and a proposal soon.

**Comment by rawkode** [comment]
@mjslane I've requested a quote from a local agency and I'll get back to you as soon as I can

**Comment by rawkode** [comment]
Hi @mjslane, we've now contacted 4 independent BSL interpreters. Hopefully have an update soon.

**Comment by rawkode** [comment]
Couldn't make this happen
