### ISSUE TITLE
Pre-conference Social

### ISSUE THREAD

**Issue by rawkode** [KubeHuddle/KubeHuddle#15]
We're opting against hosting an exclusive "speaker dinner" as found at most conferences.

Instead, we'll be having a pre-conference social where all attendees and speakers are invited.

We'll cover the cost of food and drinks for our speakers, and depending on sponsorship we'll try to get our attendees some free food and drinks too.

I would imagine we should expect around 40% of our attendees to come to the pre-conference social, though we'll require registration so that we can confirm numbers closer to the event.

**Comment by rawkode** [comment]
@amouat Updated the description with some more context.

Let's assume 25 speakers/organizers/volunteers, plus around 60 attendees.

So we need a space for 80-100 people that does food and drinks.

If the place we're looking at can cater to more people, up to 150, that would be ideal. But we can negotiate on expecting around 80?

**Comment by rawkode** [comment]
@amouat ControlPlane have offered to run a CTF and I'd like to do some Klustered challenges.

Perhaps the pre-conference social could be somewhere with ample space for laptops, board games, and some drinks nibbles?

Would your co-lo space be adequate?

**Comment by amouat** [comment]
Currently waiting on a reply from Codebase. I think I may have to chase them

**Comment by amouat** [comment]
Got reply from codebase. Also note: https://twitter.com/judy2k/status/1551659794725015554

**Comment by mjslane** [comment]
akva may be a possibility. They used to be free for large parties in the upstairs lounge.

**Comment by rawkode** [comment]
BrewDog Lothian Road have offered upstairs on the Sunday and we have an option of Angel's Share DevilCut room on the Monday.

Both offer a buffet, if we wish.

You think this would work, @mjslane ?

**Comment by rawkode** [comment]
BrewDog Lothian Road booked.

Oct 2nd, 1800-2200
