### ISSUE TITLE
Hotel Blocks

### ISSUE THREAD

**Issue by rawkode** [KubeHuddle/KubeHuddle#32]

**Comment by rawkode** [comment]
@amouat Could you reach out to the Point O hotel, next to the EICC and see if we can get a block from them too, please?

**Comment by amouat** [comment]
Hilton offer is decent!

**Comment by amouat** [comment]
Point-a aren't going to help us:

> Hi Adrian
>
> Thanks for coming back to us, we do not offer bedrooms on an allocation basis. Group bookings must be confirmed and with a deposit.
>
> Only thing I can suggest is if your guests want to book our hotel they can sign up to become an Alist member and get 10% discount on our website. https://www.pointahotels.com/get-a-deal/#

**Comment by AverageMarcus** [comment]
@rawkode @amouat Do you have the details for the hotel? If so i can get a PR up to add it to the website if you like? :)

**Comment by AverageMarcus** [comment]
@rawkode wanna merge https://github.com/KubeHuddle/KubeHuddle/pull/47 so the details are on the website too? 🙏
