### ISSUE TITLE
Ticket Giveaways at Local Events

### ISSUE THREAD

**Issue by rawkode** [KubeHuddle/KubeHuddle#37]
What events can we give some tickets away at and promote?

**Comment by rawkode** [comment]
- [ ] @amouat to list local Edinburgh groups here
- [ ] @rawkode to list local Glasgow groups here
- [ ] Major UK groups?

**Comment by amouat** [comment]
I'm involved with:
 - Cloud Native & Kubernetes Edinburgh
 - Docker Edinburgh (nothing organised currently, which is my fault)

There's also techmeetup which is being resurrected https://www.meetup.com/techmeetup/events/287159006/ (I definitely won't make that one, but if anyone else wants to go, that would be great)

There's codebase as well, could offer codebase residents a discount? And finally there's judy2k slack which is mainly Edinburgh based and very active.

I'm sure there's a bunch more I'm not aware of, especially for given languages or groups.
